import os
import sys

# Ensure the console can handle Unicode output
sys.stdout.reconfigure(encoding='utf-8')

# Dictionary of words with their Arabic translations
words_translations = {
    "Abandonner": "يتخلى",
    "Accepter": "يقبل",
    "Accident": "حادث",
    "Accomplir": "ينجز",
    "Accrocher": "يعلق",
    "Accueillir": "يستقبل",
    "Acheter": "يشتري",
    "Action": "عمل",
    "Adapter": "يتكيف",
    "Admettre": "يعترف",
    "Admirer": "يعجب",
    "Agréable": "ممتع",
    "Aider": "يساعد",
    "Aiguille": "إبرة",
    "Aimer": "يحب",
    "Air": "هواء",
    "À l'étranger": "في الخارج",
    "Alcool": "كحول",
    "Aller": "يذهب",
    "Allumer": "يشعل",
    "Allemagne": "ألمانيا",
    "Ami": "صديق",
    "An": "سنة",
    "Angleterre": "إنجلترا",
    "Animal": "حيوان",
    "Anniversaire": "عيد ميلاد",
    "Annuler": "يلغي",
    "Août": "أغسطس",
    "à pied": "سيراً على الأقدام",
    "Appareil photo": "كاميرا",
    "Appeler": "يتصل",
    "Apprendre": "يتعلم",
    "Arbre": "شجرة",
    "Argent": "مال",
    "Assiette": "طبق",
    "Aujourd'hui": "اليوم",
    "Aussi": "أيضاً",
    "Automne": "خريف",
    "Autre": "آخر",
    "Avec مع فتح البنصر": "مع",
    "Avion": "طائرة",
    "Appartenir à": "ينتمي إلى",
    "Appétit": "شهية",
    "Apprécier": "يقدر",
    "Armoire": "خزانة",
    "Arrêt": "توقف",
    "Arrêter": "يوقف",
    "Arroser": "يسقي",
    "Artiste": "فنان",
    "Assidu": "مجتهد",
    "Athènes": "أثينا",
    "Automatique": "تلقائي",
    "Autorisation": "إذن",
    "Avare": "بخيل",
    "Avertir": "يحذر",
    "Avoir": "لديه",
    "Avoir froid": "يشعر بالبرد",
    "Avoir sommeil": "يشعر بالنعاس",
    "Bagage": "أمتعة",
    "Balayer": "يكنس",
    "Bateau": "قارب",
    "Bataille": "معركة",
    "Bâtiment": "مبنى",
    "Beau": "جميل",
    "Beaucoup": "كثيراً",
    "Beurre": "زبدة",
    "Bibliothèque": "مكتبة",
    "Bientôt": "قريباً",
    "Blanc": "أبيض",
    "Bleu": "أزرق",
    "Bombe": "قنبلة",
    "Bravo": "برافو",
    "Bœuf": "لحم بقر",
    "Cacher": "يختبئ",
    "Cadeaux": "هدايا",
    "Café": "قهوة",
    "Calculer": "يحسب",
    "Calme": "هادئ",
    "Canapé": "أريكة",
    "Capital": "عاصمة",
    "Carré": "مربع",
    "Ceinture": "حزام",
    "Cercle": "دائرة",
    "Cerise": "كرز",
    "Chaise": "كرسي",
    "Chaleur": "حرارة",
    "Chance": "حظ",
    "Changer": "يغير",
    "Chat": "قط",
    "Chaud": "حار",
    "Chauffeur": "سائق",
    "Chèque": "شيك",
    "Chercher": "يبحث",
    "Cheveux": "شعر",
    "Choisir": "يختار",
    "Ciel": "سماء",
    "Cigarette": "سيجارة",
    "Clé": "مفتاح",
    "Colère": "غضب",
    "Combien": "كم",
    "Commander": "يطلب",
    "Comment": "كيف",
    "Commerce": "تجارة",
    "Communication": "اتصال",
    "Comprendre": "يفهم",
    "Conduire": "يقود",
    "Corps": "جسم",
    "Couple": "زوج",
    "Couteaux": "سكاكين",
    "Cœur": "قلب",
    "D'accord": "موافق",
    "d'une façon": "بطريقة ما",
    "danger": "خطر",
    "danse": "رقص",
    "décrire": "يصف",
    "demi": "نصف",
    "démocratie": "ديمقراطية",
    "dentiste": "طبيب أسنان",
    "dieu": "الله",
    "devant": "أمام",
    "devoir": "واجب",
    "difficile": "صعب",
    "dimanche": "الأحد",
    "dire": "يقول",
    "direction": "اتجاه",
    "discuter": "يناقش",
    "distance": "مسافة",
    "donc": "إذاً",
    "donner": "يعطي",
    "dormir": "ينام",
    "double": "مزدوج",
    "douleur": "ألم",
    "drôle": "مضحك",
    "dur": "صعب",
    "Échanger": "يبادل",
    "école": "مدرسة",
    "économie": "اقتصاد",
    "écouter": "يستمع",
    "écrire": "يكتب",
    "électrique": "كهربائي",
    "en colère": "غاضب",
    "encore": "مرة أخرى",
    "enfant": "طفل",
    "enfin": "أخيراً",
    "ensemble": "معاً",
    "entrée": "مدخل",
    "entreprise": "شركة",
    "envoyer": "يرسل",
    "erreur": "خطأ",
    "essayer": "يحاول",
    "essentiel": "أساسي",
    "étage": "طابق",
    "étoile": "نجمة",
    "étudier": "يدرس",
    "Europe": "أوروبا",
    "expliquer": "يشرح",
    "Facile": "سهل",
    "faire attention": "ينتبه",
    "famille": "عائلة",
    "farine": "طحين",
    "Femme": "امرأة",
    "fermé": "مغلق",
    "Février": "فبراير",
    "fille": "بنت",
    "fils": "ابن",
    "forêt": "غابة",
    "four": "فرن",
    "fourchette": "شوكة",
    "France": "فرنسا",
    "frappe": "ضربة",
    "frère": "أخ",
    "fumer": "يدخن",
    "futur": "مستقبل",
    "Gagnant": "فائز",
    "gagner": "يربح",
    "gauche": "يسار",
    "glace": "جليد",
    "goût": "طعم",
    "grain de raisin": "حبة عنب",
    "Grandir": "يكبر",
    "groupe": "مجموعة",
    "heure": "ساعة",
    "hier": "أمس",
    "histoire": "قصة",
    "hiver": "شتاء",
    "homme": "رجل",
    "idée": "فكرة",
    "important": "مهم",
    "intelligent": "ذكي",
    "international": "دولي",
    "interroger": "يستجوب",
    "invitation": "دعوة",
    "jamais": "أبداً",
    "janvier": "يناير",
    "je": "أنا",
    "jeu": "لعبة",
    "jeudi": "الخميس",
    "jeune": "شاب",
    "jouer": "يلعب",
    "journaux": "صحف",
    "joyeux": "سعيد",
    "juge": "قاضٍ",
    "juin": "يونيو",
    "jusqu'à": "حتى",
    "juste": "فقط",
    "kilomètres": "كيلومترات",
    "kilos": "كيلوجرامات",
    "laboratoire": "مختبر",
    "langage": "لغة",
    "large": "واسع",
    "lavabo": "مغسلة",
    "laver": "يغسل",
    "lentement": "ببطء",
    "libre": "حر",
    "lire": "يقرأ",
    "lisse": "ناعم",
    "liste": "قائمة",
    "livre": "كتاب",
    "Lumière": "ضوء",
    "lundi": "الاثنين",
    "Mademoiselle": "الآنسة",
    "maintenant": "الآن",
    "manger": "يأكل",
    "marché": "سوق",
    "marcher": "يمشي",
    "mariage": "زواج",
    "matériel": "مواد",
    "mauvais": "سيئ",
    "même": "نفسه",
    "Merci": "شكراً",
    "métro": "مترو",
    "ministre": "وزير",
    "Minuit": "منتصف الليل",
    "miroir": "مرآة",
    "montrer": "يظهر",
    "morte": "ميت",
    "mot": "كلمة",
    "musique": "موسيقى",
    "neige": "ثلج",
    "nez": "أنف",
    "noble": "نبيل",
    "noir": "أسود",
    "nombre": "عدد",
    "non": "لا",
    "normal": "عادي",
    "nourriture": "طعام",
    "nous": "نحن",
    "nouveau": "جديد",
    "novembre": "نوفمبر",
    "Observer": "يراقب",
    "occupé": "مشغول",
    "octobre": "أكتوبر",
    "Oncle": "عم",
    "opportunité": "فرصة",
    "oreille": "أذن",
    "oublier": "ينسى",
    "ouvrir": "يفتح",
    "Quand": "متى",
    "question": "سؤال",
    "Recette": "وصفة",
    "réfrigérateur": "ثلاجة",
    "regarder": "يشاهد",
    "remercier": "يشكر",
    "rencontrer": "يقابل",
    "repas": "وجبة",
    "répéter": "يكرر",
    "reporter": "مراسل",
    "responsable": "مسؤول",
    "rester": "يبقى",
    "résultats": "نتائج",
    "retourner": "يعود",
    "Réunir": "يجتمع",
    "Riche": "غني",
    "rivière": "نهر",
    "rouge": "أحمر",
    "route": "طريق",
    "S'il vous plaît": "من فضلك",
    "sac à dos": "حقيبة ظهر",
    "salle": "غرفة",
    "saluer": "يحيي",
    "samedi": "السبت",
    "sauter": "يقفز",
    "sauver": "ينقذ",
    "scientifique": "عالم",
    "si": "إذا",
    "signal": "إشارة",
    "silence": "صمت",
    "simple": "بسيط",
    "société": "مجتمع",
    "sonnette": "جرس",
    "souffrir": "يعاني",
    "soupe": "حساء",
    "sourire": "يبتسم",
    "sport": "رياضة",
    "stupide": "غبي",
    "sucre": "سكر",
    "sud": "جنوب",
    "suivre": "يتابع",
    "supplier": "يتوسل",
    "surprise": "مفاجأة",
    "Toujours": "دائماً",
    "travail": "عمل",
    "tribunal": "محكمة",
    "trouver": "يجد",
    "théâtre": "مسرح",
    "tête": "رأس",
    "tache": "بقعة",
    "tante": "عمة",
    "taper à la machine": "يكتب على الآلة الكاتبة",
    "tasse": "فنجان",
    "téléphoner": "يتصل هاتفياً",
    "thème": "موضوع",
    "tomate": "طماطم",
    "toucher": "يلمس",
    "tout": "كل شيء",
    "tout droit": "مباشرة",
    "travailleur": "عامل",
    "Paquet": "حزمة",
    "parapluie": "مظلة",
    "pardonner": "يغفر",
    "parents": "والدين",
    "paris": "باريس",
    "parler": "يتحدث",
    "passager": "راكب",
    "pâtisserie": "معجنات",
    "payer": "يدفع",
    "peindre": "يرسم",
    "peintre": "رسام",
    "peinture": "رسم",
    "piqué": "شوكة",
    "pleurer": "يبكي",
    "poêle": "مقلاة",
    "pommade": "مرهم",
    "pont": "جسر",
    "poule": "دجاجة",
    "poulet": "دجاج",
    "pourquoi": "لماذا",
    "premier": "أول",
    "prénom": "اسم أول",
    "président": "رئيس",
    "presque": "تقريباً",
    "problème": "مشكلة",
    "professeur": "أستاذ",
    "programme": "برنامج",
    "propre": "نظيف",
    "prouver": "يثبت",
    "publique": "عام",
}

# Directory containing the files to rename
directory = r'C:\Users\LENOVO\Desktop\sigml'
 

# Get the list of files in the directory
files = os.listdir(directory)

# Iterate over each file in the directory
for filename in files:
    # Get the base name without the extension
    base_name = os.path.splitext(filename)[0]
    # Check if the base name is in the dictionary
    if base_name in words_translations:
        # Get the translation
        translation = words_translations[base_name]
        # Form the new filename
        new_filename = f"{translation}.sigml"
        # Get the full paths
        old_file = os.path.join(directory, filename)
        new_file = os.path.join(directory, new_filename)
        # Rename the file
        os.rename(old_file, new_file)
        print(f"Renamed '{filename}' to '{new_filename}'")
    else:
        print(f"No translation found for '{filename}'")



